### ISSUE TITLE
Add Ruby Cheatsheet

### ISSUE THREAD

**Issue by lifeparticle** [markets/awesome-ruby#1037]
A Ruby Cheatsheet for beginners.
https://github.com/lifeparticle/Ruby-Cheatsheet

**Comment by markets** [comment]
Hi @lifeparticle 👋🏼 and thanks for contributing in Awesome Ruby! 

Unfortunately, in this collection we don't usually add this kind of resources, like: guides, books, blogs...  Maybe you can try in other collections, for example: https://github.com/dreikanter/ruby-bookmarks

**Comment by lifeparticle** [comment]
Thank you @markets for the link!
