### ISSUE TITLE
Add strong_migrations

### ISSUE THREAD

**Issue by robertmfv** [markets/awesome-ruby#1079]
https://github.com/ankane/strong_migrations 

strong_migrations used for catching unsafe migrations in development

  ✓  Detects potentially dangerous operations
  ✓  Prevents them from running by default
  ✓  Provides instructions on safer ways to do what you want

Supports PostgreSQL, MySQL, and MariaDB

**Comment by markets** [comment]
Do you want to send a pull request @robertmfv? I think it fits nice under the "Database Tools" section.
