### ISSUE TITLE
Add FXRuby

### ISSUE THREAD

**Issue by Vucius** [markets/awesome-ruby#1080]
I found this gem when i surfed on the [net](https://qiita.com/drumath2237/items/16ab7247f30000cb7583)
it looks good and it still keeps maintaining

**Comment by markets** [comment]
Thanks @Vucius 👍🏼

Do you want to send a pull request? I think it will fit well under https://github.com/markets/awesome-ruby#gui

**Comment by Vucius** [comment]
> Thanks @Vucius 👍🏼
> 
> Do you want to send a pull request? I think it will fit well under https://github.com/markets/awesome-ruby#gui

😭sry,I didn't see ur reply and I haven't tried `send a pull request` this before.I was also thoughting about how to comminicate with 'larskanis'
