### ISSUE TITLE
Update AXLSX

### ISSUE THREAD

**Issue by jayanthdeejay** [markets/awesome-ruby#1095]
[AXLSX](https://github.com/randym/axlsx), listed under [Spreadsheets and Documents](https://github.com/markets/awesome-ruby#spreadsheets-and-documents), is being maintained by the community now. Readme from original repo is as follows:   
     
`You are viewing the original unmaintained axlsx project. Please visit the current community maintained version at https://github.com/caxlsx/caxlsx`    
    
New: [CAXLSX](https://github.com/caxlsx/caxlsx)

**Comment by markets** [comment]
Thanks for the ping @jayanthdeejay! Do you want to send a pull request to update it?
