### ISSUE TITLE
Add Notion Ruby Client

### ISSUE THREAD

**Issue by phacks** [markets/awesome-ruby#1101]
[notion-ruby-client](https://github.com/orbit-love/notion-ruby-client): a client for the Notion API, following in the footsteps of [slack-ruby-client](https://github.com/slack-ruby/slack-ruby-client). I think it qualifies as per the contribution guide!

I’m open to create a PR if you think it’d be a good fit.

**Comment by markets** [comment]
hi @phacks! It seems a good candidate, feel free to send a PR.

**Comment by phacks** [comment]
Done in https://github.com/markets/awesome-ruby/pull/1102!
