### ISSUE TITLE
Add Github stars #

### ISSUE THREAD

**Issue by chiniara** [markets/awesome-ruby#1119]
It would be nice if the links had a GitHub stars number to the side so we know which ones is the currently most used one, or at least more popular.

**Comment by markets** [comment]
Hi @chiniara 👋🏼 I'm actually building a web-app that contains that info and much more (trending repos, ranking by country, multiple langs, interviews, ...). Please take a look: https://opensource-heroes.com/awesome/ruby

**Comment by chiniara** [comment]
Hey, thats awesome!
I will take a look. Thank you.
