### ISSUE TITLE
Add Sidekiq Lifecycle Hooks

### ISSUE THREAD

**Issue by WillTaylor22** [markets/awesome-ruby#1127]
A short but sweet library to improve the performance of most rails apps in 5 minutes.

https://github.com/WillTaylor22/sidekiq_lifecycle_hooks

**Comment by markets** [comment]
Hello @WillTaylor22! As per [contrib guides](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#quality-standard), this is still too fresh for this list (only ~300 downloads).
