### ISSUE TITLE
Add Rack-CORS

### ISSUE THREAD

**Issue by HungNgKh** [markets/awesome-ruby#1134]
[rack-cors ](https://github.com/cyu/rack-cors) - Support configuring  Cross-Origin Resource Sharing on any web framework that is Rack compatible

RubyGems: https://rubygems.org/gems/rack-cors

**Comment by markets** [comment]
Hello @HungNgKh, 

Which category you think it will fit better?

**Comment by markets** [comment]
Closing... Maybe too obscure for this list? No category was proposed for months, and I can't find a good one neither.
