### ISSUE TITLE
Consider adding `positioning` gem?

### ISSUE THREAD

**Issue by brendon** [markets/awesome-ruby#1141]
I maintain the `acts_as_list` and `ranked-model` gems and have created a new one called `positioning`:

https://github.com/brendon/positioning

Would you consider adding it to the list here? :)

**Comment by markets** [comment]
Hello @brendon,

If the project meets our guidelines (https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#quality-standard) we can consider it for sure.

**Comment by brendon** [comment]
Thanks @markets :) Looks like we're at 17k downloads so far so I'll come back when we're at 30k :D Only been published for 3 months.

**Comment by markets** [comment]
Hello @brendon 👋 It seems that downloads are over 60k actually, so time to send a PR?

**Comment by brendon** [comment]
Far out, that was fast! :) I'll get right on it :)
