### ISSUE TITLE
Add AnnotateRb

### ISSUE THREAD

**Issue by drwl** [markets/awesome-ruby#1143]
[AnnotateRb](https://github.com/drwl/annotaterb) - A Ruby Gem that adds annotations to your Rails models and route files.

I used to be a maintainer in the old gem Annotate, but made a hardfork last year and have been actively maintaining it. I would also consider removing the old gem as it's not actively maintained. The last release was over 2 years ago (v3.2.0 was released Feb 2022).

https://rubygems.org/gems/annotaterb

**Comment by drwl** [comment]
@markets let me know if there's any qualms about adding the gem. I can also submit a PR with the requested change if you want.

**Comment by markets** [comment]
Closing this one @drwl, as the main discussion is happening on #1145.
