### ISSUE TITLE
Data YAML/JSON backed and site redesign

### ISSUE THREAD

**Issue by markets** [markets/awesome-ruby#189]
Continuation of some thoughts in https://github.com/markets/awesome-ruby/issues/60#issuecomment-61476505

**Summary**: Move resources (links) to YAML (instead of Readme) with more metadata (fetch via apis: stars, last commit, downloads ...) and build the site via scripts. Still easy to contribute, powerful static site => better access/filter info. Just an idea to think about, any kind of suggestions are really welcome. 

Another good example of JSON data backend + tagging: http://googlecloudplatform.github.io/

@AlexLarra started a simple script to convert the Readme to a YAML: https://gist.github.com/AlexLarra/0ac306bfae319a940909

**Comment by maxmeyer** [comment]
@markets 
Maybe you want to look at https://github.com/middleman/middleman-directory there's a [data file](https://github.com/middleman/middleman-directory/tree/master/data) where information is held for `middleman-extensions`

@tdreyno

Would it be easy to fork and re-use the directory for another project? Any suggestions?

**Comment by tdreyno** [comment]
@maxmeyer You're welcome to fork/copy/change whatever helps you out. We're probably going to rebuild the directory in the latest Ember release at some point in the future.

**Comment by markets** [comment]
Thanks @maxmeyer @tdreyno !!

I recently found that project and this is exactly the idea I had in mind (if we finally take the decision to rewrite AwesomeRuby). I also like: http://googlecloudplatform.github.io/ and http://motion-toolbox.com/ (middleman project).

Would be nice to extract main funtionality of middleman-directory to a middleman extension (released as a gem). Lately, there is a lot of directory/collection (organized by tags) projects and I suspect most of them would use this extension :100:

**Comment by maxmeyer** [comment]
@markets I'm not sure if this - the extension - makes sense. I think most logic is part of the ember.js-logic, correct @tdreyno? Maybe you can use `bower` to build a re-usable component. If you need help on the ruby-stuff I think I can help, but I'm definitively no JavaScript-expert. :smile: 

But no doubt, `middleman` is a great tool to build such a site. BTW: I used it for some internal projects lately which are a bit beyond websites: Building and Deploying [proxy.pac](http://de.wikipedia.org/wiki/Proxy_Auto-Config)-files + developing and building custom error-pages with inlined assets - javascript, images, stylesheets - for some some commercial proxy. I am very very satisfied that I chose `middleman`. @tdreyno Thanks for developing this: I really enjoy it using it on a daily basis.

**Comment by markets** [comment]
Ah @maxmeyer, yes, the most logic is the front-end side (consuming the json generated when building the site). But anyway, it would be very useful to wrap a middleman project with that Ember code, ready to go: just edit YAMLs, customize some variables of personal data, color variables ... and deploy!

PD: Agreed, middleman is really awesome :top: :gem:
