### ISSUE TITLE
BrowseEverything

### ISSUE THREAD

**Issue by mbrookes** [markets/awesome-ruby#259]
In the dug-out: https://github.com/projecthydra-labs/browse-everything

**Comment by markets** [comment]
Seems `projecthydra-labs` organization is hosting beta versions of programs, from their site:

> Experiments, Works-in-progress, and Beta versions of gems and apps. May be suitable for production use, but awaiting broader adoption.

I'll keep it open for some time more: 36k downloads and a really useful feature...   

Would be nice if someone from `projecthydra-labs` can clarify us that situation, is it producion ready software? 

(Ping @mbklein, as a major contributor)

**Comment by mbklein** [comment]
Hi! Thanks for the ping, @markets.

`projecthydra-labs` is an incubator for `projecthydra`. `browse-everything` currently meets the criteria for promotion out of labs, but we haven't gotten around to actually doing it yet. It is in production use by several projects including the [Avalon Media System](http://avalonmediasystem.org/) and Penn State University's [ScholarSphere](https://scholarsphere.psu.edu/) (via the [Sufia](https://github.com/projecthydra/sufia) gem).

It has strong community support and several active contributors. I wouldn't hesitate to use it.

**Comment by markets** [comment]
Hi @mbklein, good to hear that :+1: 

Do you want to send a PR?

**Comment by mbklein** [comment]
Yes, I will. This conversation spurred me to nominated `browse-everything` for promotion out of labs, and it's reached consensus approval, so I'll probably wait and submit a PR to you afterward so we don't have to change the link later.

Since it's a file uploader that pulls from cloud providers, would you want it in the Cloud section or the File Upload section?

**Comment by markets** [comment]
That's amazing news. Regarding category, both seems acceptable... but probably under Cloud feels conceptually more comfortable. Thanks! By the way, really useful tool :+1: (would be nice to announce the project on Reddit Ruby room, RubyFlow, RubyDaily ... Surely more people would like it)
