### ISSUE TITLE
Eldritch

### ISSUE THREAD

**Issue by hollingberry** [markets/awesome-ruby#269]
Under the "processes & threads" sections. Here's a link: https://github.com/beraboris/eldritch

**Comment by markets** [comment]
Hi @hollingberry,

Thank you for submitting suggestions :+1: 

Not sure about section, I'm also thinking in `Concurrency`... thoughts?

**Comment by hollingberry** [comment]
What's the difference between  `Concurrency` and `Processes & Threads`? It seems like some gems (like [parallel](http://github.com/grosser/parallel)) could easily go in either category.

Neither [childprocess](https://github.com/jarib/childprocess) and [posix-spawn](https://github.com/rtomayko/posix-spawn) really belongs in concurrency though... so combining the categories probably isn't the best idea...

**Comment by markets** [comment]
Yes, you're right, merging both categories seems a bad idea, but sometimes isn't clear enough where to add some resources. Some projects can fit well in different categories... Would be good to add a kind of "tags", not just "categories" as it is now (future enhancements ??) Or renaming some categories?

So, for now, both categories seems ok IMHO.

**Comment by markets** [comment]
Closing for now, please re-open in case you want to resume that discussion. Thanks!
