### ISSUE TITLE
AnywayConfig

### ISSUE THREAD

**Issue by palkan** [markets/awesome-ruby#296]
Any-source configuration for Rails plugins and applications https://github.com/palkan/anyway_config

**Comment by markets** [comment]
Hi @palkan, thanks a lot for share this resource. Anyway, IMHO we already have a lot of configuration plugins and the idea of this project is to collect only most popular and used by the community.

We can keep the issue opened for some time and wait for people feedback.

Similar situations, for example, here: https://github.com/markets/awesome-ruby/pull/93, https://github.com/markets/awesome-ruby/pull/193
