### ISSUE TITLE
Small gems

### ISSUE THREAD

**Issue by obduk** [markets/awesome-ruby#304]
Hi, first of can I say this is a very useful page.

One problem I have found with it is a lot of the gems on the list have very few download numbers, some even below a hundred. Although I don't want to discourage new gems, I often find gems with so few download numbers are either not properly maintained, or are not greatly peer reviewed.

Would it be a good idea to have a rough download count next to each one, or a tag for new gems?

**Comment by mbrookes** [comment]
I agree with the concern, but adding counts to each listing and keeping it
updated would be very time consuming as the list is manually curated.

I tend to add useful looking, well structured gems but which are new or
with low star count as issues rather than PRs.

Some guidance in the contributing read me on minim age and star count might
be a good idea, but then you can have old abandoned gems that were popular
in their time still qualify, so it wouldn't fool-proof.

Tangentially, I also think there's a case to be made for splitting out
Rails-only and generic Ruby gems into separate lists.

>

**Comment by markets** [comment]
Hi @obduk,

I also agree with the concern, but as @mbrookes said, isn't so maintainable. After all, this is just a markdown file (=> parsed via GitHub API to build a site) + issues. 

We started discussing this idea in: https://github.com/markets/awesome-ruby/issues/60.

I think `Awesome Ruby` should be a place to find most awesome Ruby related projects, bests tools to build/test/debug/analyze/deploy/package... Ruby apps nowadays and really really useful in general. That context also includes new gems (if they fit contribution guides). 

The idea is to collect MVP resources per category, but once here (a category scope), the idea is to explore/review those top filtered tools by oneself. Numbers are usually good indicators, but sometimes awesomeness isn't just numbers...

> Some guidance in the contributing read me on minim age and star count might
be a good idea, but then you can have old abandoned gems that were popular
in their time still qualify, so it wouldn't fool-proof.

Probably would be a good start. For example: stars + watchers > 100, active last year. Of course, not all projects are hosted on GitHub, so for those cases and for other exceptions we can use GH issues to discuss about it. 

Sometimes I think in moving the project to static site backed with YAML, would be nice to have quantitative measures, metadata, categories, tagging... and have an script to recompute data via APIs, just an idea right now... ++maintainability

Another idea: write a script (aka `awesome-ruby-doctor`), run it locally to detect low level resources, in terms of stars, downloads, activity... would be really helpul to maintain that list in an easy way.

**Comment by markets** [comment]
Ah @obduk, what gems are you talking about? 

New issues/PRs suggesting deletions (tagged with this [label](https://github.com/markets/awesome-ruby/labels/delete%20link)) are also welcome, after all, community-driven is the key point. 

Thanks!

**Comment by obduk** [comment]
Sorry for the slow reply.

1. I see the problem with maintenance / read https://github.com/markets/awesome-ruby/issues/60. Would a first step be turning it into a GitHub pages? Then I could look into adding some Javascript that would get the numbers for the gems.
2. I think maybe adding something to the Contribution guide saying a minimum number of downloads or something to score them on might be helpful.
3. I will have a look through and try and make some pull requests for ones I've found which I don't think are maintained etc.

Thanks.

**Comment by markets** [comment]
Hi @obduk,

1) We already have a GitHub Pages site (http://awesome-ruby.com/) built with Flatdoc (js tool that parses markdown via GitHub API => html + lateral menu). Workflow is pretty simple right now (no need to deploy `gh-pages` branch, site auto-updated). Anyway, as you read in https://github.com/markets/awesome-ruby/issues/60 and https://github.com/markets/awesome-ruby/issues/189, I'm valorating the idea to move to different approaches, but just some thoughts...

The script (awesome-ruby-doctor) to detect "bad" resources is quite simple/useful too, and we shouldn't rewrite the whole site. We also can run script via Travis :100: 

2) Yes, totally agree, and we can discuss "exceptions" using GH issues.

3) :+1: would be really helpful, like the script but manually.
