### ISSUE TITLE
Addressable

### ISSUE THREAD

**Issue by sporkmonger** [markets/awesome-ruby#310]
Obviously, I'm biased, but at 20m downloads and actively maintained since 2006, I think it's safe to say this one's mature and battle-tested.

Under the "Misc" section most likely. "Navigation" didn't seem right, and "HTTP" is all about clients.

URL: https://github.com/sporkmonger/addressable

**Comment by markets** [comment]
Hi @sporkmonger,

Probably `Core Extensions` is also a good place. 

The project seems mature and well-mantained, not sure if it's too much specific for this collection. Let's keep the issue open and wait for more community feedback (+1 or -1 should be enough).

Thanks a lot!

**Comment by Ch4s3** [comment]
+1
