### ISSUE TITLE
Ruby Weekly

### ISSUE THREAD

**Issue by mbrookes** [markets/awesome-ruby#383]
Congrats on making top of the news on Ruby Weekly!

http://rubyweekly.com/issues/241

**Comment by markets** [comment]
Wow @mbrookes, so awesome!

![captura de pantalla 2015-04-10 a la s 10 48 04](https://cloud.githubusercontent.com/assets/576701/7084591/203d1134-df6f-11e4-9299-6d6e86a64319.png)

Thanks @peterc and all contributors, you rock!

**Comment by AlexLarra** [comment]
![](http://t3.ehcdn.com/es/images/9/4/1/img_puto_amo_7149_orig.gif)

**Comment by fleveque** [comment]
An issue about being mentioned on an issue!

![](http://www.reactiongifs.com/r/arsenio.gif)

Congrats crack!

![](http://www.reactiongifs.com/r/winner.gif)

**Comment by mbrookes** [comment]
Well if you're going to be top of one, might as well be top of another: http://greenruby.org/grn-114.html

Wonder where they get their news from? ;)
