### ISSUE TITLE
Adding github stars

### ISSUE THREAD

**Issue by bertomartin** [markets/awesome-ruby#384]
It's still hard to decide which gem to choose (from each category) by browsing the awesome ruby website. It would be nice to see the number of github stars next to the gem.

**Comment by markets** [comment]
Hi @bertomartin,

We already start to discuss a similar topics/ideas here: https://github.com/markets/awesome-ruby/issues/304, https://github.com/markets/awesome-ruby/issues/189

Some quantitative data would be useful, but the main goal of this project isn't to collect most starred repos... After all, this is just a markdown file.

Also, projects under a category are, sometimes, complementaries and they provide different features/approaches.
