### ISSUE TITLE
QR-code

### ISSUE THREAD

**Issue by ferdinandrosario** [markets/awesome-ruby#439]
Hi recently I wanted to find a library to create QR code, immediately awesome-ruby is the first repository I check in but, unfortunately there is no QR-code library and section to add below. 

So could you create a section? and I'm happy to add "https://github.com/whomwah/rqrcode" under that...

I found the above repository actively developing and maintaining.

**Comment by markets** [comment]
Hi @ferdinandrosario, yep, agreed, a good QR library would be nice. By now, we can add it under `Misc`, and create the category in case we found more related resources. Would you like to send a PR?

Thanks :+1:

**Comment by Ch4s3** [comment]
:+1:

**Comment by ferdinandrosario** [comment]
Sure I will send a PR

**Comment by ferdinandrosario** [comment]
:+1:

**Comment by markets** [comment]
Closed by #442
