### ISSUE TITLE
Add Words Counted: Ruby word counter and text analyser.

### ISSUE THREAD

**Issue by abitdodgy** [markets/awesome-ruby#463]
[Words Counted](https://github.com/abitdodgy/words_counted) A Ruby word counter and text analyser.

**Comment by markets** [comment]
Thanks for the suggestion! I think it fits good under `NATURAL LANGUAGE PROCESSING`, what do you think?

**Comment by abitdodgy** [comment]
@markets thanks for taking the time. I think so too. I will soon add ngram functionality, so it will be firmly in that area.

**Comment by markets** [comment]
You're welcome! thanks for this amazing library :ok_hand: :top: 

Do you want to send a PR? Thanks

**Comment by abitdodgy** [comment]
Closing in favour of #464
