### ISSUE TITLE
Rpush. The push notification service for Ruby.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [markets/awesome-ruby#513]
https://github.com/rpush/rpush

Rpush aims to be the de facto gem for sending push notifications in Ruby.

**Comment by markets** [comment]
:+1:

**Comment by SuperMasterBlasterLaser** [comment]
Also Please add this: https://github.com/adelevie/parse-ruby-client

Parse Ruby Client.

Helps developers to connect to Parse.com service to make push notifications

**Comment by markets** [comment]
@SuperMasterBlasterLaser As you surely know, Parse will shut down:

> Parse's hosted services will be fully retired on January 28, 2017.

So: 
- +1 for `rpush`
- -1 `parse-ruby-client`

Do you want to send a PR for Rpush? Thanks!
