### ISSUE TITLE
API pagination

### ISSUE THREAD

**Issue by kurenn** [markets/awesome-ruby#529]
Checkout https://github.com/IcaliaLabs/pager-api for API fast pagination, with kaminari and will paginate support.

I could be added under pagination

**Comment by markets** [comment]
Hi @kurenn, thanks for sharing! Looks useful :+1: but still to fresh to be on this collection. Just 1.332 downloads according RubyGems. Let's keep it open for some time and see how the project evolves.

**Comment by kurenn** [comment]
Sure, we use it very often, and I agree with you! let's wait and see

**Comment by markets** [comment]
:wave: I'm going to close this one for now. Please re-open in case you want to resume/continue this discussion (or the project reaches higher popularity/downloads, or you think it really deserves a place here). Thanks :+1:

**Comment by kurenn** [comment]
Thanks for the follow up, I just added support for pagy, which is the fastest ruby pagination gem out there, or seems like it, this is the link - https://github.com/IcaliaLabs/pager-api/tree/support/pagy
