### ISSUE TITLE
Rails app builder

### ISSUE THREAD

**Issue by kurenn** [markets/awesome-ruby#530]
Platter is a command line rails app generator to help you build Rails barebones as fast as possible. It includes devise and some other cool stuff. https://github.com/IcaliaLabs/platter

**Comment by markets** [comment]
Hi @kurenn, we already have a pretty decent list of [Rails generators](https://github.com/markets/awesome-ruby#rails-application-generators). What are the advantages of `platter` regarding the others?

**Comment by kurenn** [comment]
Well, is a simple setup we use at Icalia, it just adds a simple configuration for a testing environment, error handling, user handling, figaro for environment variables. It speeds things up at the beginning, this way every project we have follows the same bare bones.

**Comment by markets** [comment]
Yes, apps generators are really useful, but current projects in that category seems more well-known and feature rich. Will close this one.
