### ISSUE TITLE
Link to Ruby Best Practices...

### ISSUE THREAD

**Issue by jcoady9** [markets/awesome-ruby#540]
I found this website/repo that I think would be great to include in this repo. It has information on best practices with ruby but I'm not sure what section this would fall under.....

http://best-ruby.com/

**Comment by markets** [comment]
Hi @jcoady9, yes, it's a pretty nice resource. What do you think about [coding-style-guides](https://github.com/markets/awesome-ruby#coding-style-guides)? Thanks

**Comment by jcoady9** [comment]
Yup, that works.

**Comment by markets** [comment]
Closed in favour of #542
