### ISSUE TITLE
active_reloader

### ISSUE THREAD

**Issue by ilatif** [markets/awesome-ruby#558]
[active_reloader](https://github.com/ilatif/active_reloader_rb) - Rails gem that reloads browser as soon as any file is changed

**Comment by markets** [comment]
Hi @ilatif, thank you for sharing this! 

Last week I've encountered https://github.com/Shopify/fleek, they look pretty similar in purpose, no? Both seem too fresh for that list at this moment ... both projects are under 1k downloads, according to RubyGems. But this feature is really cool, so let's keep this open, we can review it later.

**Comment by ilatif** [comment]
Hi @markets, thanks for commenting.

Yeah, `fleek` looks quite similar but as per it's documentation, it only updates when changes are made to CSS files and is using `action_cable` under-the-hood. Whereas, `active_reloader` is just plain Ruby and would refresh browser if user saves any file, be it a Rails controller, a JavaScript file or some CSS file.

Thanks for keeping the issue open for later review :+1: :clap:.

**Comment by markets** [comment]
That's right @ilatif!

We'll review it in some months :eyes:

**Comment by ilatif** [comment]
Cool! :ok_hand:

**Comment by ilatif** [comment]
Hi @markets.

`active_reloader` gem has just crossed 1k downloads on RubyGems. It would be awesome to add `active_reloader` to the list, but if you think we should wait for more downloads, then I' am totally fine with this as well 😄 .

Thanks

**Comment by markets** [comment]
Hi @ilatif, sorry, IMO 1k downloads are small number, let's wait for more use. Thanks!

**Comment by markets** [comment]
Closing this for now. It seems little active during latest years and community seems is moving to `webpacker` or independent front-end apps.
