### ISSUE TITLE
rails_enhancer

### ISSUE THREAD

**Issue by bacosmin** [markets/awesome-ruby#559]
Yesterday i lunched rails_enhancer 
https://rubygems.org/gems/rails_enhancer
https://github.com/bacosmin/rails_enhancer

**Comment by markets** [comment]
Thanks @bacosmin, but this gem is actually too fresh for this collection. Imagine if we add all the gems...

**Comment by markets** [comment]
Hi @bacosmin! I'm going to close this one. Seems little active last year. Please re-open in case you want to resume/continue this discussion (or the project reaches higher popularity/downloads 👍 ). Thanks!
