### ISSUE TITLE
Uru

### ISSUE THREAD

**Issue by ghost** [markets/awesome-ruby#565]
[Uru](https://bitbucket.org/jonforums/uru) is a lightweight, multi-platform command line tool that helps you use the multiple rubies (currently MRI, JRuby, and Rubinius) on your 32/64-bit Linux, OS X, or Windows systems.

This is a great tool to manage multiple versions of ruby on Windows. Can you add it under [Environment Management](https://github.com/markets/awesome-ruby#environment-management) section?

**Comment by markets** [comment]
Do you think we can consider this as a popular resource or widely-used tool in the Ruby ecosystem?

**Comment by 0x01f7** [comment]
I use [Uru](https://bitbucket.org/jonforums/uru) in favor of [pik](https://github.com/vertiginous/pik), a similar tool which has more than 800 stars on GitHub, but no longer maintained. The maintainer of pik recommand its users look at Uru as alternative.

In my opinion, it's a popular resource or widely-used tool on Windows. :-)

**Comment by markets** [comment]
Thanks for adding this information, really helpful! I'll wait for Windows users to provide some feedback, I actually don't know any Rubyst coding on that platform ...

**Comment by enkessler** [comment]
@markets I develop primarily on Windows and, yes, Uru is pretty handy if I need to swap between different versions of Ruby on a regular basis.

**Comment by markets** [comment]
Thanks for the info @enkessler! Do you want to send a PR?

**Comment by enkessler** [comment]
I can do that, yeah. I need to open a few PRs anyway for some of my own gems. Might as well get all of them out of the way at once. :)

**Comment by markets** [comment]
👍 remember, as per contrib guides, https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#contribution-guidelines:

> Add one link per pull-request.

So this way we can discuss/merge each project in an isolated way. Thanks!

**Comment by enkessler** [comment]
Correct, it will not be one big PR. It will be many PRs to the point where your spam filter will trigger. ;)
