### ISSUE TITLE
remove chgems?

### ISSUE THREAD

**Issue by 0x01f7** [markets/awesome-ruby#566]
[chgems](https://github.com/postmodern/chgems) has been deprecated. I think we should remove this link according to [Contribution Guidelines#Quality standard](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#quality-standard).

**Comment by markets** [comment]
yep, 100% agree, I'll do it later

**Comment by jdickey** [comment]
`chgems` has been deprecated in favour of [`gem_home`](https://github.com/postmodern/gem_home#readme), which looks as though it deserves a spot on your "watch for later" list (at ~65 stars).

**Comment by markets** [comment]
thanks @jdickey for pointing this out! it was already there!
