### ISSUE TITLE
Add weka gem to Machine Learning section

### ISSUE THREAD

**Issue by paulgoetze** [markets/awesome-ruby#567]
May I suggest to add [weka](https://rubygems.org/gems/weka) to the machine learning selection?
Basically It is a rewrite of [ruby-band](https://rubygems.org/gems/ruby-band) and also works with JRuby 9.0.0.0+.

**Comment by markets** [comment]
hi @paulgoetze, thanks for sharing this!

So, is ruby-band kind of deprecated? If so, we can just replace the link.

**Comment by paulgoetze** [comment]
@markets At least ruby-band seems kind of unmaintained, yes. The last action by the maintainer seemed to be in 2014. 
I tried to implement all the functionality of ruby-band in weka and I think it should cover everything but the DatabaseLoader/DatabaseSaver (I have plans to add this soon, too) and the server functionality (I haven‘t used the server stuff before, so I don‘t really know what this is about or whether this should actually be included in the gem).

**Comment by markets** [comment]
Yes, more than 1 year without activity and last changes was commited by yourself... probably the best option here is to replace ruby-band with weka. Do you want to send a PR? Thanks!

**Comment by paulgoetze** [comment]
Ok, cool, will do.
