### ISSUE TITLE
termit is defunct

### ISSUE THREAD

**Issue by nerab** [markets/awesome-ruby#570]
Google blocks the API they are using; see https://github.com/pawurb/termit

**Comment by markets** [comment]
oooh! sad news :( I really like this tool!

Do you know guys if there is any alternative API to make it work, again?

cc @pawurb

**Comment by pawurb** [comment]
I don't have time to fix it right away. Please remove it for now and I will ping you if I manage to get it functional again. I will look into bing translation api's. If you have more api suggestions they are welcome.

**Comment by markets** [comment]
Thanks a lot for the answer @pawurb! Ok, I'm going to remove it for now.

As per this Quora post https://www.quora.com/Which-is-a-good-reliable-free-language-translation-API-available, the only free available translation API is Bing Translator.

Would be really nice to have this working again 🔝 💎 . Keep it up!
