### ISSUE TITLE
Voting system

### ISSUE THREAD

**Issue by markets** [markets/awesome-ruby#60]
In order to ensure higher quality of resources, could be a good idea to introduce some kind of simple voting system.
- 5 postive votes (+1) => add it to the list (or merge PR if any)
- 5 negative votes (-1) => remove it from list

What do you think? We can add a VOTING.md file explaining the rules or just add a section into the CONTRIBUTING.md document.

**Comment by markets** [comment]
Let's use GitHub reactions and comments to let the community to express their thoughts. Added to contribution guides here https://github.com/markets/awesome-ruby/commit/56ecd65d0d7c221a0103344b2dfc0d2e2eb65787

**Comment by bernsie** [comment]
would it be feasible to implement github's [`.github` folder templates](https://github.com/blog/2111-issue-and-pull-request-templates) to enforce these guidelines?

**Comment by markets** [comment]
hi @bernsie, do you mean to copy the content of CONTRIBUTING.md file to a PULL_REQUEST_TEMPLATE.md? Would be nice if GH allow symlinks for that... 

PS. this works right now https://github.com/blog/1184-contributing-guidelines

**Comment by bernsie** [comment]
something along those lines yes.

**Comment by markets** [comment]
@jbernsie pushed [here](https://github.com/markets/awesome-ruby/blob/5a43340d7e2ccacddcb03938fea1a33b5523efba/.github/PULL_REQUEST_TEMPLATE.md), what do you think about content (or formatting)?

**Comment by jbernsie** [comment]
@markets Looks good to me man 👍 no complaints haha
