### ISSUE TITLE
bulk_insert

### ISSUE THREAD

**Issue by gmichokostas** [markets/awesome-ruby#605]
https://github.com/jamis/bulk_insert - A little ActiveRecord extension for helping to insert lots of rows in a single insert statement.

**Comment by markets** [comment]
It fits good under [ORM extensions](https://github.com/markets/awesome-ruby#ormodm-extensions), Import subsection. Do you want to send a PR? Thanks!

**Comment by gmichokostas** [comment]
Pull request opened https://github.com/markets/awesome-ruby/pull/606
