### ISSUE TITLE
Is awesome-ruby website open sourced?

### ISSUE THREAD

**Issue by cqcn1991** [markets/awesome-ruby#610]
Just want to know how it read the content and formatted in web pages from github repo.

**Comment by markets** [comment]
Hi @cqcn1991, 

Yes the webapp is also open source, take a look at this branch: https://github.com/markets/awesome-ruby/tree/gh-pages. It's built with Flatdoc 👌 (http://ricostacruz.com/flatdoc/) by @rstacruz. Basically, it pulls the content via an ajax call and the it parses the markdown file via a JS library to convert it to html. 

Any kind of feedback or improvements to the site are much appreciated.

**Comment by cqcn1991** [comment]
thanks alot. 
I also want to build an awesome list. But I find awesome lists are always too long to read, so maybe there are better way to present the information. And I think your website is a great example.
