### ISSUE TITLE
Redis Store

### ISSUE THREAD

**Issue by raky291** [markets/awesome-ruby#629]
[redis-store](http://redis-store.org/) - Redis Store provides a full set of stores (Cache, I18n, Session, HTTP Cache) for modern Ruby frameworks like: Ruby on Rails, Sinatra, Rack, Rack::Cache and I18n. It supports object marshalling, timeouts, single or multiple nodes, and namespaces.

or

[redis-store](https://github.com/redis-store/redis-store) - Namespaced Rack::Session, Rack::Cache, I18n and cache Redis stores for Ruby web frameworks.

I like more the first option, it's just my personal opinion.

**Comment by markets** [comment]
Hi @raky291, I also prefer the former! Do you want to send a PR? Not sure about the section since it provides different things ...
