### ISSUE TITLE
Don't know where should be repo?

### ISSUE THREAD

**Issue by khusnetdinov** [markets/awesome-ruby#663]
I collect information for ruby language with examples. It includes OOP, Patters, DS, Algorithms, Threads with references to source and books. 
Look here https://github.com/khusnetdinov/ruby.fundamental

Where can I put this?

**Comment by fanjieqi** [comment]
Maybe the [resources](https://github.com/markets/awesome-ruby#resources).

**Comment by khusnetdinov** [comment]
Thanks, I will send PR

**Comment by khusnetdinov** [comment]
PR https://github.com/markets/awesome-ruby/pull/664

**Comment by khusnetdinov** [comment]
Were problems with previous PR, fixed now only one commit.

**Comment by markets** [comment]
Hi @khusnetdinov, thanks for sharing! I think it would fit better under [Coding Style Guides](https://github.com/markets/awesome-ruby#coding-style-guides), as it's similar to https://github.com/franzejr/best-ruby. Also, in resources we add different stuff:

> Where to discover new Ruby libraries, projects and trends.

If you guys are agree, we just need to update #666 (😈 )

**Comment by khusnetdinov** [comment]
Updated!

**Comment by khusnetdinov** [comment]
Ping, Are guys agree or not?

**Comment by markets** [comment]
Merged @khusnetdinov 👍
