### ISSUE TITLE
Adding lists as items

### ISSUE THREAD

**Issue by arbox** [markets/awesome-ruby#679]
Hi @markets 
I wonder if it is possible to add whole lists as items, particularly two lists of NLP related libraries in the [Natural Language Processing](https://github.com/markets/awesome-ruby#natural-language-processing) section:
- https://github.com/diasks2/ruby-nlp
- https://github.com/arbox/nlp-with-ruby

I'll provide a pool request if you're fine with this proposal.

**Comment by markets** [comment]
Hi @arbox, yes please! Those are pretty relevant resources for people looking for NLP on the Ruby ecosystem.
