### ISSUE TITLE
camping.io redirects to unrelated website

### ISSUE THREAD

**Issue by kofronpi** [markets/awesome-ruby#682]
camping.io redirects to an unrelated website (born2invest). (in web frameworks)

**Comment by markets** [comment]
Hi @kofronpi, thanks! I just updated the URL pointing to GitHub.

I also found these issues: 
- Main repo: https://github.com/camping/camping/issues/97  
- Site repo: https://github.com/camping/camping.io/issues/4

As per @sfcgeorge comments:

> As the camping.io site is a gh-pages one, I think the CNAME file could just be deleted then it will be available again at camping.github.io/camping.io

**Comment by kofronpi** [comment]
Hi @markets, no worries! Good you opened issues there too.
