### ISSUE TITLE
Tensorflow Ruby wrapper

### ISSUE THREAD

**Issue by jjgh** [markets/awesome-ruby#699]
Please add Tensorflow Ruby wrapper link.

**Comment by markets** [comment]
Good one! But actually, I think the project is under heavy development/changes and in a kind of "alpha" stage: https://github.com/somaticio/tensorflow.rb/milestone/1

On the radar 👀 ! https://github.com/tensorflow/tensorflow/issues/50

**Comment by jjgh** [comment]
I see, but I think it's still helpful to list it, in order to let the majority of the people know it's actually a thing, and perhaps to even direct new potential contributors to it, or simply early adopters who could motivate development even more.
Just my thought.. :)

**Comment by markets** [comment]
Hi @jjgh, I understand your arguments but to be honest, I'm not sure about this addition at this point... So let's keep it open for more time to "track" the status and to let people leave their opinion. Thanks for your feedback!

**Comment by markets** [comment]
Couple of related links:
- https://github.com/ankane/tensorflow
- https://github.com/jedld/tensor_stream

**Comment by jjgh** [comment]
@markets looks like @ankane's Tensorflow managed to achieve what https://github.com/somaticio/tensorflow.rb/ was after..
