### ISSUE TITLE
http://rubyland.news

### ISSUE THREAD

**Issue by markets** [markets/awesome-ruby#704]
Under https://github.com/markets/awesome-ruby#resources

http://rubyland.news

**Comment by hd719** [comment]
Hello I am new to Open Source and I would like to contribute to this project.

-Thank you!

**Comment by markets** [comment]
Hi @hd719! Everybody is really welcome to contribute here, just check this guides: https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md#how-can-i-contribute
