### ISSUE TITLE
Web Framework: rack-app

### ISSUE THREAD

**Issue by adamluzsi** [markets/awesome-ruby#713]
Dear awesome-ruby maintainers, 

Please add rack-app project to the curated list if you think that the project worth to be there! :)

link:
https://github.com/rack-app/rack-app

**Comment by adamluzsi** [comment]
Is tere something I need to do in order to help you 
@markets ? ^~^

**Comment by markets** [comment]
Hi @adamluzsi, could you please send a PR? I'm currently on vacations and I'm checking this via mobile phone ... 😃  thanks!

**Comment by adamluzsi** [comment]
Sure! I didn't have the courage to do so by my self alone
