### ISSUE TITLE
Wrong isnt maintained any more

### ISSUE THREAD

**Issue by Kapenaar** [markets/awesome-ruby#719]
It seems that the Wrong test assertion project is no longer maintained. The last commit was in 2014, there are long list of critical open issues and even the hello world example doesn't work with the latest release [see here](https://github.com/sconover/wrong/issues/46).

I think this should be removed from awesome-ruby as it is not awesome any more, just frustrating.

**Comment by markets** [comment]
@Kapenaar agreed! make sense to remove it from here. Could you please send a PR? Thanks!
