### ISSUE TITLE
Wrapper Based

### ISSUE THREAD

**Issue by RichOrElse** [markets/awesome-ruby#768]
[WrapperBased](https://github.com/RichOrElse/wrapper-based) - Unobtrusive DCI library slightly similar to [Surrounded](https://github.com/saturnflyer/surrounded). An alternative approach to ActiveSupport::Concern. Instead of including mixins in models, any class including controllers can serve as context where object and behavior are combined.

**Comment by markets** [comment]
Hi @RichOrElse, thanks for sharing! 

Still too fresh for this list (2k downloads and 6 stars on GH), but promising. Keep it up!
