### ISSUE TITLE
green-onion (visual testing tool)

### ISSUE THREAD

**Issue by ShanWehttam** [markets/awesome-ruby#781]
(https://github.com/mobomo/green_onion)

**Comment by markets** [comment]
Hi again @ShanWehttam I'm -1 on this one, latest commit was 5 years ago and I think there are other and better maintained tools nowadays.

**Comment by ShanWehttam** [comment]
Hello there,
No problem.  I agree, it's becoming rather ancient... i opt for Applitools instead
