### ISSUE TITLE
awesome print

### ISSUE THREAD

**Issue by danielb2** [markets/awesome-ruby#788]
Seems awesome print somehow got left out 😂

https://github.com/awesome-print/awesome_print

**Comment by markets** [comment]
hi @danielb2 you're totally right! That is really a useful tool and a vastly used gem (more than 40 millions downloads)! I'm not sure about the category: maybe CLI Utilities or IRB? 

Thanks!

**Comment by danielb2** [comment]
Would say more CLI Utils than IRB as it can be used independently (and can be used with pry too)

**Comment by markets** [comment]
Yes, probably fits better under [CLI Utils](https://github.com/markets/awesome-ruby#cli-utilities). Do you want to send a PR? Thanks!
