### ISSUE TITLE
setupWatirCucumber- A gem for setup BDD automation with Cucumber and Watir Framework

### ISSUE THREAD

**Issue by GedersonChiquesi** [markets/awesome-ruby#791]
[SetupWatirCucumber](https://github.com/GedersonChiquesi/setupWatirCucumber) -  A gem for setup BDD automation with Cucumber and Watir Framework

**Comment by markets** [comment]
hi @GedersonChiquesi and thanks for sharing! 

Seems a useful project to generate some boilerplate, but we can't consider it an essential Ruby library at this point ("Generally used and useful to the community" as per contrib guides), and also, we can say the project is too fresh for this list (0 stars, ~240 downloads). So I'm going to close this issue for now... if the project reaches higher popularity and madurity after some time, please don't hesitate to reopen! Thanks 👍
