### ISSUE TITLE
hipchat_smart: Create a hipchat bot that is really smart and so easy to expand

### ISSUE THREAD

**Issue by MarioRuiz** [markets/awesome-ruby#804]
https://github.com/MarioRuiz/hipchat_smart

**Comment by markets** [comment]
> Atlassian and Slack have forged a new strategic partnership. We'll be discontinuing Hipchat and Stride, and are providing a migration path to Slack for all our customers.

https://www.atlassian.com/blog/announcements/new-atlassian-slack-partnership
