### ISSUE TITLE
I want to add seattlerb/hoe but in which category should I do it ?

### ISSUE THREAD

**Issue by ghost** [markets/awesome-ruby#816]
[seattlerb/hoe](/seattlerb/hoe)

Maybe **Rake/Rubygems helpers** ?

**Comment by markets** [comment]
Hi @breakfast1, good question, maybe [Package Management#Gems](https://github.com/markets/awesome-ruby#package-management)? I don't like to create such specific, and single-project, categories.

**Comment by breakfast1** [comment]
@markets thanks for replying.

I think putting hoe in the category you mentioned is not the best way around.

Maybe if I make a list of proper alternatives to hoe (such as [blackwinter/hen](/blackwinter/hen) then we can create the aforementioned category **Rake/Rubygems helpers** ?

**Comment by markets** [comment]
you're welcome @breakfast1!

To be honest `blackwinter/hen` doesn't seem a popular resource for the Ruby ecosystem right now. Personally, I don't use Hoe neither, Bundler already provides a quite good gem template via a command (https://bundler.io/v1.16/man/bundle-gem.1.html): 

    > bundle gem GEM_NAME 

Btw, `Hoe` has ~5 millions of downloads, so it has a place here, we only need to find a proper category.
