### ISSUE TITLE
Academic writing on the Ruby programming language

### ISSUE THREAD

**Issue by oshanz** [markets/awesome-ruby#821]
http://rubybib.org/

 On this page we list research projects using Ruby and peer-reviewed papers and articles that cover Ruby implementation or use Ruby, including alternative implementations such as JRuby.

**Comment by markets** [comment]
Hi @oshanz and thanks a lot for sharing! 

However, we don't actually list here links like this one: about papers, learning material, books, tutorials ... `Awesome Ruby` focuses on libraries, apps and software. 

You can find similar proposals in #562, #620, #663, #808, ...
