### ISSUE TITLE
nice_hash presented at EuRuKo 18

### ISSUE THREAD

**Issue by MarioRuiz** [markets/awesome-ruby#841]
Presented on EuRuKo 18 at the github lounge

https://github.com/MarioRuiz/nice_hash

You can easily generate all the hashes you want following the criteria you specify. Many other features coming to Hash class like the methods 'bury' or select_key, access the keys like methods: my_hash.my_key.other_key. You will be able to generate thousands of different hashes just declaring one and test easily APIs based on JSON for example.

**Comment by markets** [comment]
Hi again @MarioRuiz and thanks for sharing your projects! Similar situation like in #842, still too fresh (~500 downloads).
