### ISSUE TITLE
string_pattern easily generate and validate strings

### ISSUE THREAD

**Issue by MarioRuiz** [markets/awesome-ruby#842]
string_pattern gem

https://github.com/MarioRuiz/string_pattern

You can easily generate strings supplying a very simple pattern. Also, you can validate if a text fulfills a specific pattern or even generate a string following a pattern and returning the wrong length, value... for testing your applications.

**Comment by markets** [comment]
Hi @MarioRuiz and thanks for sharing! This project seems so fresh for this collection, only ~1k downloads. Let's keep this issue open for some time, we'll see how the project evolves and if it reaches some popularity and usage.
