### ISSUE TITLE
Add ajax-datatable-rails in Data Visualization

### ISSUE THREAD

**Issue by n-rodriguez** [markets/awesome-ruby#843]
Hit there! Can you please add [ajax-datatables-rails](https://github.com/jbox-web/ajax-datatables-rails)

> ajax-datatables-rails is a wrapper around DataTables ajax methods that allow synchronization with server-side pagination in a Rails app.

The latest release is around 6k downloads (within a month).

The total download is around 400k.

Thank you!

**Comment by markets** [comment]
Hi again @n-rodriguez! We usually don't add gems that are front-end libraries wrappers for Sprockets, but this one in particular offers a more integrated solution. So, I'm not sure, let's keep this discussion open and wait for other people feedback. 

Thanks.

**Comment by n-rodriguez** [comment]
> We usually don't add gems that are front-end libraries wrappers for Sprockets, but this one in particular offers a more integrated solution

It's not really a wrapper for Sprocket but more a specialized rendering object for the jQuery Datatable lib. It's a presenter object that renders to JSON with filtering/sorting capabilities.
