### ISSUE TITLE
Add syslogger in Logging

### ISSUE THREAD

**Issue by n-rodriguez** [markets/awesome-ruby#844]
Hit there! Can you please add [syslogger](https://github.com/crohr/syslogger)

> A drop-in replacement for the standard Logger Ruby library, that logs to the syslog instead of a log file. Contrary to the SyslogLogger library, you can specify the facility and the syslog options.

The latest release is around 200k downloads.

The total download is around 1.4m.

Thank you!

**Comment by markets** [comment]
Hi @n-rodriguez nice one, 1,4m downloads :ok_hand: seems a really used project!

Would you like to fill a pull request? Thanks for sharing it!

**Comment by n-rodriguez** [comment]
Done! Thank you!
