### ISSUE TITLE
Add fast_blank

### ISSUE THREAD

**Issue by n-rodriguez** [markets/awesome-ruby#853]
Hi there! Can you please add [fast_blank](https://github.com/SamSaffron/fast_blank)?

> Provides a C-optimized method for determining if a string is blank

It's about 3M downloads, but I don't know in which section it should goes :/

**Comment by n-rodriguez** [comment]
Maybe a new `Optimizations` section?

**Comment by n-rodriguez** [comment]
We could also add 
* [bootsnap](https://github.com/Shopify/bootsnap) (Boot large Ruby/Rails apps faster) about 5M downloads
* [yajl-ruby](https://rubygems.org/gems/yajl-ruby/versions/1.2.1) (Ruby C bindings to the excellent Yajl JSON stream-based parser library.) 23M downloads

**Comment by markets** [comment]
Yeah @n-rodriguez! please go ahead, seems a good idea to me too and 3 good resources to start.

**Comment by markets** [comment]
Closed by #854
