### ISSUE TITLE
Add primes-utils to Scientific

### ISSUE THREAD

**Issue by jzakiya** [markets/awesome-ruby#893]
`primes-utils` is a Rubygem which provides a suite of extremely fast utility methods for testing and generating primes. Consider it a Swiss-army knife for all things primes.

https://github.com/jzakiya/primes-utils
https://rubygems.org/gems/primes-utils
https://www.scribd.com/doc/266461408/Primes-Utils-Handbook

**Features**

- fast
- flexible
- accurate
- easy to use

**Comment by markets** [comment]
Hi @jzakiya 👋 and thanks again for sharing resources! Similar situation to #894

**Comment by jzakiya** [comment]
Similar response to https://github.com/markets/awesome-ruby/issues/894.

It appears you've taken no time to actually look at the gem to see what it does, and how well it does it.

I know of no other available utility, in any language, that does all the things `primes-utils` does, and as fast, accurate, and easy. I see a pattern here.
