### ISSUE TITLE
Zomeki CMS

### ISSUE THREAD

**Issue by Daniel-ltw** [markets/awesome-ruby#922]
https://github.com/zomeki/zomeki3

Notice this on my github Discover list.

**Comment by markets** [comment]
Hi @Daniel-ltw and thanks for sharing! Btw, this doesn't seem a very well-known resource compared to other projects in that category. I'd be -1 on this, but let's keep it open some time to let people comment and express their opinions.

**Comment by Daniel-ltw** [comment]
Based on what I am reading on their site, it seems more popular with the Japanese market. 

I think they might only have Japanese for their localization. 

Another thing to keep in mind, their company Sitebridge, seems to have another product, [Joruri CMS](https://github.com/joruri/joruri-cms).
