### ISSUE TITLE
Runbook

### ISSUE THREAD

**Issue by dcchambers** [markets/awesome-ruby#940]
[Runbook](https://github.com/braintree/runbook) is a new automation framework from Braintree. Runbook provides a Ruby DSL and set of tools to build system automation rules and workflows.

It's highly versatile and can be used as a Ruby library within your app or by itself. It supports remote execution via SSHKit, headless/automated mode, Tmux integration, and an extensible DSL.

**Comment by markets** [comment]
@dcchambers I'm going to close this issue, no need to have an issue and a PR opened at the same time.

**Comment by dcchambers** [comment]
Makes sense 👍
