### ISSUE TITLE
huqua (quick check database without access rails console)

### ISSUE THREAD

**Issue by hdchinh** [markets/awesome-ruby#950]
> My repo:  https://github.com/hdchinh/huqua

Hi Author

The first, I want to say thank you for creating a great repository, many awesome libs that very helpful also help me save a lot of time.

The second, I create this issue because I have just created a simple lib. When my friend who has a Frontend Dev working with rails, he wants to view a simple picture of his database without access via rails console or other tools UI, so I create this project.  Too fresh, of course,  but I think it's a little fun. 

Like this:

![gif description](https://i.imgur.com/IC4B7iR.gif)

Please, let me know your  thoughts,

best regard,

**Comment by markets** [comment]
Hi @hdchinh and thanks a lot for sharing here! This project seems useful 👍, but still too "fresh" for this list, only ~1k downloads according RubyGems. Let's keep the issue open for some time to see if the project reaches some popularity in the community.
