### ISSUE TITLE
Add Falcon server

### ISSUE THREAD

**Issue by megatux** [markets/awesome-ruby#998]
It was nice to see _iodine_ web server but I think [Falcon](https://github.com/socketry/falcon) also has to be present, too. It has almost the triple of stars than iodine, has [some commercial support](https://github.com/socketry/falcon#priority-business-support) and it's in production use at [iCook](https://icook.tw)  and [RubyAPI](https://rubyapi.org).

**Comment by markets** [comment]
Yep, agree @megatux. Do you want to send a PR?

**Comment by megatux** [comment]
> Yep, agree @megatux. Do you want to send a PR?

ok!

**Comment by megatux** [comment]
The PR is #999
